services:
  craftbox:
    image: willtda/craftbox:latest
    pull_policy: always
    container_name: craftbox
    labels:
      yantr.app: "craftbox"
      yantr.service: "Game Server"
    ports:
      - "6464:6464"
      - "25500-25600:25500-25600/tcp"
      - "25500-25600:25500-25600/udp"
    environment:
      SERVER_PORT: ${PORT:-6464}
      NODE_ENV: ${NODE_ENV:-development}
      TRUST_PROXY: ${TRUST_PROXY:-false}
    volumes:
      - craftbox:/app/data
    restart: unless-stopped

volumes:
  craftbox:
