services:
  gupt:
    image: ghcr.io/besoeasy/gupt:latest
    container_name: gupt
    labels:
      yantr.app: "gupt"
      yantr.service: "Web UI"
    ports:
      - "8000"
    restart: unless-stopped
