services:
  agent-zero:
    image: agent0ai/agent-zero:latest
    container_name: agent-zero
    labels:
      yantr.app: "agent-zero"
      yantr.service: "Web UI"
    restart: on-failure
    ports:
      - "3005"
    volumes:
      - agent_zero_data:/a0
    environment:
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-*}

volumes:
  agent_zero_data:
