services:
  vert:
    image: ghcr.io/vert-sh/vert:latest
    container_name: vert
    labels:
      yantr.app: "vert"
      yantr.service: "Web UI"
    ports:
      - "3000"
    restart: unless-stopped
