services:
  web:
    image: ghcr.io/getumbrel/hermes-agent-umbrel:latest
    container_name: hermes-agent
    hostname: hermes
    init: true
    user: "1000:1000"
    labels:
      yantr.app: "hermes-agent"
      yantr.service: "Web UI"
    restart: on-failure
    depends_on:
      - gateway
    ports:
      - "18789"
    volumes:
      - hermes_data:/opt/data
    environment:
      HERMES_API_KEY: ${HERMES_API_KEY:-yantr12hermes}
      GATEWAY_HEALTH_URL: http://gateway:8642

  gateway:
    image: nousresearch/hermes-agent:latest
    container_name: hermes-gateway
    labels:
      yantr.app: "hermes-agent"
      yantr.service: "Gateway"
    command: gateway run
    stop_grace_period: 1m
    restart: on-failure
    volumes:
      - hermes_data:/opt/data
    environment:
      HERMES_UID: "1000"
      HERMES_GID: "1000"
      API_SERVER_ENABLED: "true"
      API_SERVER_HOST: "0.0.0.0"
      API_SERVER_KEY: ${HERMES_API_KEY:-yantr12hermes}

volumes:
  hermes_data:
