FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    tor \
    wget \
    && rm -rf /var/lib/apt/lists/*

COPY tor-entrypoint.sh /tor-entrypoint.sh
RUN chmod +x /tor-entrypoint.sh

ENTRYPOINT ["/tor-entrypoint.sh"]
