services:
  moviepilot:
    stdin_open: true
    tty: true
    image: jxxghp/moviepilot-v2:latest
    container_name: moviepilot
    hostname: moviepilot
    ports:
      - "3000"
      - "3001"
    volumes:
      - moviepilot-config:/config
      - moviepilot-core:/moviepilot/.cache/ms-playwright
      - /media:/media
    environment:
      NGINX_PORT: 3000
      PORT: 3001
      PUID: 0
      PGID: 0
      UMASK: "000"
      TZ: ${TZ:-Asia/Shanghai}
      SUPERUSER: ${SUPERUSER:-admin}
      SUPERUSER_PASSWORD: ${SUPERUSER_PASSWORD:-changeme}
    restart: unless-stopped
    labels:
      yantr.app: "moviepilot"
      yantr.service: "Media Automation"

volumes:
  moviepilot-config:
    name: moviepilot-config
  moviepilot-core:
    name: moviepilot-core
